[package]
name = "git-pijul"
version = "0.1.0"
authors = ["pe@pijul.org <pe@pijul.org>"]

[dependencies]
libpijul = { path = "libpijul" }
git2 = "*"
rand = "*"
chrono = "*"
env_logger = "*"
clap = "*"
log = "*"

[profile.release]
opt-level = 1
debug = true
